project_name: rotom

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: .
    binary: rotom
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE.txt

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'

release:
  github:
    owner: shravanasati
    name: rotom
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## What's Changed
  footer: |
    **Full Changelog**: https://github.com/shravanasati/rotom/compare/{{ .PreviousTag }}...{{ .Tag }}

# Uncomment and configure these sections when you have package repositories set up
# brews:
#   - name: rotom
#     repository:
#       owner: shravanasati
#       name: homebrew-tap
#       branch: main
#       token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     directory: Formula
#     homepage: https://github.com/shravanasati/rotom
#     description: "Show pokemon image on terminal"
#     license: MIT
#     skip_upload: auto
#     test: |
#       system "#{bin}/rotom --version"
#     install: |
#       bin.install "rotom"

# scoops:
#   - name: rotom
#     repository:
#       owner: shravanasati
#       name: scoop-bucket
#       branch: main
#       token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     homepage: https://github.com/shravanasati/rotom
#     description: "Show pokemon image on terminal"
#     license: MIT
